config/routes.rb
Scs::Application.routes.draw do
  resources :sistemas

  resources :servidores

  resources :linguagens

   root :to => 'sistemas#index'

end

app/models/linguagem.rb
class Linguagem < ActiveRecord::Base
  attr_accessible :nome

  validates_presence_of :nome
  
  def homologada?
    ['Java', 'Ruby', 'Scala'].include? self.nome
  end
end

app/models/servidor.rb
class Servidor < ActiveRecord::Base
  attr_accessible :ip, :nome

  validates_presence_of :nome
  validates_presence_of :ip
  
  has_and_belongs_to_many :sistemas, :join_table => "sistemas_servidores"
end

app/models/sistema.rb
class Sistema < ActiveRecord::Base
  attr_accessible :nome, :linguagem, :sistema_id

  belongs_to :linguagem
  has_and_belongs_to_many :servidores, :join_table => "sistemas_servidores"
  
  validates :nome, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/linguagens_controller.rb
class LinguagensController < ApplicationController
  # GET /linguagens
  # GET /linguagens.json
  def index
    @linguagens = Linguagem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @linguagens }
    end
  end

  # GET /linguagens/1
  # GET /linguagens/1.json
  def show
    @linguagem = Linguagem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @linguagem }
    end
  end

  # GET /linguagens/new
  # GET /linguagens/new.json
  def new
    @linguagem = Linguagem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @linguagem }
    end
  end

  # GET /linguagens/1/edit
  def edit
    @linguagem = Linguagem.find(params[:id])
  end

  # POST /linguagens
  # POST /linguagens.json
  def create
    @linguagem = Linguagem.new(params[:linguagem])

    respond_to do |format|
      if @linguagem.save
        format.html { redirect_to @linguagem, notice: 'Linguagem criada com sucesso.' }
        format.json { render json: @linguagem, status: :created, location: @linguagem }
      else
        format.html { render action: "new" }
        format.json { render json: @linguagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /linguagens/1
  # PUT /linguagens/1.json
  def update
    @linguagem = Linguagem.find(params[:id])

    respond_to do |format|
      if @linguagem.update_attributes(params[:linguagem])
        format.html { redirect_to @linguagem, notice: 'Linguagem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @linguagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linguagens/1
  # DELETE /linguagens/1.json
  def destroy
    @linguagem = Linguagem.find(params[:id])
    @linguagem.destroy

    respond_to do |format|
      format.html { redirect_to linguagens_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/servidores_controller.rb
class ServidoresController < ApplicationController
  # GET /servidores
  # GET /servidores.json
  def index
    @servidores = Servidor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servidores }
    end
  end

  # GET /servidores/1
  # GET /servidores/1.json
  def show
    @servidor = Servidor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @servidor }
    end
  end

  # GET /servidores/new
  # GET /servidores/new.json
  def new
    @servidor = Servidor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @servidor }
    end
  end

  # GET /servidores/1/edit
  def edit
    @servidor = Servidor.find(params[:id])
  end

  # POST /servidores
  # POST /servidores.json
  def create
    @servidor = Servidor.new(params[:servidor])

    respond_to do |format|
      if @servidor.save
        format.html { redirect_to @servidor, notice: 'Servidor was successfully created.' }
        format.json { render json: @servidor, status: :created, location: @servidor }
      else
        format.html { render action: "new" }
        format.json { render json: @servidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servidores/1
  # PUT /servidores/1.json
  def update
    @servidor = Servidor.find(params[:id])

    respond_to do |format|
      if @servidor.update_attributes(params[:servidor])
        format.html { redirect_to @servidor, notice: 'Servidor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @servidor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servidores/1
  # DELETE /servidores/1.json
  def destroy
    @servidor = Servidor.find(params[:id])
    @servidor.destroy

    respond_to do |format|
      format.html { redirect_to servidores_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sistemas_controller.rb
class SistemasController < ApplicationController
  # GET /sistemas
  # GET /sistemas.json
  def index
    @sistemas = Sistema.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sistemas }
    end
  end

  # GET /sistemas/1
  # GET /sistemas/1.json
  def show
    @sistema = Sistema.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sistema }
    end
  end

  # GET /sistemas/new
  # GET /sistemas/new.json
  def new
    @sistema = Sistema.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sistema }
    end
  end

  # GET /sistemas/1/edit
  def edit
    @sistema = Sistema.find(params[:id])
  end

  # POST /sistemas
  # POST /sistemas.json
  def create
    @sistema = Sistema.new(params[:sistema])

    respond_to do |format|
      if @sistema.save
        format.html { redirect_to @sistema, notice: 'Sistema was successfully created.' }
        format.json { render json: @sistema, status: :created, location: @sistema }
      else
        format.html { render action: "new" }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sistemas/1
  # PUT /sistemas/1.json
  def update
    @sistema = Sistema.find(params[:id])

    respond_to do |format|
      if @sistema.update_attributes(params[:sistema])
        format.html { redirect_to @sistema, notice: 'Sistema was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sistemas/1
  # DELETE /sistemas/1.json
  def destroy
    @sistema = Sistema.find(params[:id])
    @sistema.destroy

    respond_to do |format|
      format.html { redirect_to sistemas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/linguagens_helper.rb
module LinguagensHelper
end

app/helpers/servidores_helper.rb
module ServidoresHelper
end

app/helpers/sistemas_helper.rb
module SistemasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/linguagens/_form.html.erb
<%= form_for(@linguagem) do |f| %>
  <% if @linguagem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@linguagem.errors.count, "erro") %> nao permitiu que a linguagem seja salva:</h2>

      <ul>
      <% @linguagem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/linguagens/edit.html.erb
<h1>Editando linguagem</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @linguagem %> |
<%= link_to 'Voltar', linguagens_path %>

app/views/linguagens/index.html.erb
<h1>Listando linguagens</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @linguagens.each do |linguagem| %>
  <tr>
    <td><%= linguagem.nome %></td>
    <td><%= link_to 'Visualizar', linguagem %></td>
    <td><%= link_to 'Editar', edit_linguagem_path(linguagem) %></td>
    <td><%= link_to 'Apagar', linguagem, confirm: 'Tem certeza?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova Linguagem', new_linguagem_path %>

app/views/linguagens/new.html.erb
<h1>Nova linguagem</h1>

<%= render 'form' %>

<%= link_to 'Voltar', linguagens_path %>

app/views/linguagens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @linguagem.nome %>
</p>


<%= link_to 'Edit', edit_linguagem_path(@linguagem) %> |
<%= link_to 'Back', linguagens_path %>

app/views/servidores/_form.html.erb
<%= form_for(@servidor) do |f| %>
  <% if @servidor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servidor.errors.count, "erro") %> prohibited this servidor from being saved:</h2>

      <ul>
      <% @servidor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servidores/edit.html.erb
<h1>Editing servidor</h1>

<%= render 'form' %>

<%= link_to 'Show', @servidor %> |
<%= link_to 'Back', servidores_path %>

app/views/servidores/index.html.erb
<h1>Listing servidores</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Ip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @servidores.each do |servidor| %>
  <tr>
    <td><%= servidor.nome %></td>
    <td><%= servidor.ip %></td>
    <td><%= link_to 'Show', servidor %></td>
    <td><%= link_to 'Edit', edit_servidor_path(servidor) %></td>
    <td><%= link_to 'Destroy', servidor, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Servidor', new_servidor_path %>

app/views/servidores/new.html.erb
<h1>New servidor</h1>

<%= render 'form' %>

<%= link_to 'Back', servidores_path %>

app/views/servidores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @servidor.nome %>
</p>

<p>
  <b>Ip:</b>
  <%= @servidor.ip %>
</p>


<%= link_to 'Edit', edit_servidor_path(@servidor) %> |
<%= link_to 'Back', servidores_path %>

app/views/sistemas/_form.html.erb
<%= form_for(@sistema) do |f| %>
  <% if @sistema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sistema.errors.count, "error") %> prohibited this sistema from being saved:</h2>

      <ul>
      <% @sistema.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :linguagem %><br />
    <%= f.collection_select :sistema_id, Linguagem.all, :id, :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sistemas/edit.html.erb
<h1>Editing sistema</h1>

<%= render 'form' %>

<%= link_to 'Show', @sistema %> |
<%= link_to 'Back', sistemas_path %>

app/views/sistemas/index.html.erb
<h1>Listing sistemas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sistemas.each do |sistema| %>
  <tr>
    <td><%= sistema.nome %></td>
    <td><%= sistema.linguagem.nome unless sistema.linguagem.nil? %></td>

    <td><%= link_to 'Show', sistema %></td>
    <td><%= link_to 'Edit', edit_sistema_path(sistema) %></td>
    <td><%= link_to 'Destroy', sistema, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sistema', new_sistema_path %>

app/views/sistemas/new.html.erb
<h1>New sistema</h1>

<%= render 'form' %>

<%= link_to 'Back', sistemas_path %>

app/views/sistemas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @sistema.nome %>
</p>
<p>
  <b>Linguagem:</b>
  <%= @sistema.linguagem.nome unless @sistema.linguagem.nil? %>
</p>

<%= link_to 'Edit', edit_sistema_path(@sistema) %> |
<%= link_to 'Back', sistemas_path %>